/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyCraft
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittycraft.h>

#include <interfaces/kittyCraft.h>
#include <proto/exec.h>
#include <assert.h>

struct kittyCompactIFace * IkittyCraft = NULL;
static struct Library * __kittyCraftBase;
static struct kittyCompactIFace * __IkittyCraft;

/****************************************************************************/

extern struct Library * kittyCraftBase;

/****************************************************************************/

void kittyCraft_main_constructor(void)
{
    if (kittyCraftBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __kittyCraftBase = kittyCraftBase = (struct Library *)IExec->OpenLibrary("kittycraft.library", 0L);
        assert(kittyCraftBase != NULL);
    }

    __IkittyCraft = IkittyCraft = (struct kittyCompactIFace *)IExec->GetInterface((struct Library *)kittyCraftBase, "main", 1, NULL);
    assert(IkittyCraft != NULL);
}
__attribute__((section(".ctors.zzzy"))) static void
(*kittyCraft_main_constructor_ptr)(void) USED = kittyCraft_main_constructor;

/****************************************************************************/

void kittyCraft_main_destructor(void)
{
    if (__IkittyCraft)
    {
        IExec->DropInterface ((struct Interface *)__IkittyCraft);
    }
    if (__kittyCraftBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyCraftBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*kittyCraft_main_destructor_ptr)(void) USED = kittyCraft_main_destructor;

/****************************************************************************/

