/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyCraft
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittycraft.h>

#include <interfaces/kittyCraft.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * kittyCraftBase = NULL;
static struct Library * __kittyCraftBase;

/****************************************************************************/

void kittyCraft_base_constructor(void)
{
    if (kittyCraftBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __kittyCraftBase = kittyCraftBase = (struct Library *)IExec->OpenLibrary("kittycraft.library", 0L);
    assert(kittyCraftBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*kittyCraft_base_constructor_ptr)(void) USED = kittyCraft_base_constructor;

/****************************************************************************/

void kittyCraft_base_destructor(void)
{
    if (__kittyCraftBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyCraftBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*kittyCraft_base_destructor_ptr)(void) USED = kittyCraft_base_destructor;

/****************************************************************************/

