
/* This file was generated by idltool 53.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCRAFT_H
#include <libraries/kittycraft.h>
#endif

extern ULONG                VARARGS68K _kittycraft_Obtain(struct kittyCraftIFace *);
extern ULONG                VARARGS68K _kittycraft_Release(struct kittyCraftIFace *);
extern char *               VARARGS68K _kittycraft_makeLookupTable(struct kittyCraftIFace *);
extern void                 VARARGS68K _kittycraft_FreeLookupTable(struct kittyCraftIFace *, void * table);
extern void *               VARARGS68K _kittycraft_makeContext(struct kittyCraftIFace *);
extern void                 VARARGS68K _kittycraft_FreeContext(struct kittyCraftIFace *, void * table);
