
/* This file was generated by idltool 53.6. Do not edit */

#include "kittyCraft_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _kittycraft_Obtain,
    _kittycraft_Release,
    NULL,
    NULL,
    _kittycraft_makeLookupTable,
    _kittycraft_FreeLookupTable,
    _kittycraft_makeContext,
    _kittycraft_FreeContext,
    (APTR)-1
};

