#ifndef KITTYCRAFT_INTERFACE_DEF_H
#define KITTYCRAFT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCRAFT_H
#include <libraries/kittycraft.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct kittyCompactIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct kittyCompactIFace *Self);
	ULONG APICALL (*Release)(struct kittyCompactIFace *Self);
	void APICALL (*Expunge)(struct kittyCompactIFace *Self);
	struct Interface * APICALL (*Clone)(struct kittyCompactIFace *Self);
	char * APICALL (*makeLookupTable)(struct kittyCompactIFace *Self);
	void APICALL (*FreeLookupTable)(struct kittyCompactIFace *Self, void * table);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* KITTYCRAFT_INTERFACE_DEF_H */
