#ifndef INLINE4_KITTYCRAFT_H
#define INLINE4_KITTYCRAFT_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCRAFT_H
#include <libraries/kittycraft.h>
#endif
#include <interfaces/kittyCraft.h>

/* Inline macros for Interface "main" */
#define makeLookupTable() IkittyCraft->makeLookupTable() 
#define FreeLookupTable(table) IkittyCraft->FreeLookupTable((table)) 
#define makeContext() IkittyCraft->makeContext() 
#define FreeContext(table) IkittyCraft->FreeContext((table)) 

#endif /* INLINE4_KITTYCRAFT_H */
